In [1]:
import numpy as np

In [2]:
test_array = np.array(['4','5',6,7],float) # 정해준 data type으로 통일한다.
print(test_array)

[4. 5. 6. 7.]


numpy array의 구조는 c언어의 배열과 유사  
- python list 와는 다름.
- 장점 : 메모리 접근성 증가, 데이터 접근성++

In [3]:
a =[1,2,3,4,5]
b =[5,4,3,2,1]
a[0] is b[-1]

True

is(메모리 비교 연산) 으로 비교하면 그 차이를 알 수 있다.

In [4]:
a = np.array(a)
b = np.array(b)
a[0] is b[-1]

False

shape의 차원(row,col)은
차원이 증가함에 따라 한 칸씩 밀림을 볼 수 있다.

In [5]:
a = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
b = [1,2,3,4]
print(np.array(a).shape)
print(np.array(a).dtype)
print(np.array(a).ndim)
print(np.array(a).size)

print(np.array(b).shape)
print(np.array(b).dtype)
print(np.array(b).ndim)
print(np.array(b).size)


(3, 4)
int32
2
12
(4,)
int32
1
4


In [7]:
m= [[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]]
np.array(m).reshape(1,-1)
np.array(m).flatten()


array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [9]:
np.zeros(shape=(10,),dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [14]:
m = np.empty((3,4))
np.ones_like(m)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.eye(3,5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
m = np.arange(30).reshape(5,6)
np.diag(m) # 대각선 추출

array([ 0,  7, 14, 21, 28])

In [18]:
np.random.normal(0,1,10).reshape(2,5)# 이거말고도 여러가지 분포 지원

array([[-0.40147944, -0.70260575,  0.501327  ,  1.00968555,  1.02188895],
       [ 1.05809794,  0.92992447, -0.56704092, -0.64076495,  0.83532067]])

In [19]:
a= np.arange(30).reshape(5,6)
b= np.arange(30).reshape(5,6)
a*b # Element-wise operation 같은 위치에 있는 값끼리 곱해진거 나온다. dot product아님.

array([[  0,   1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100, 121],
       [144, 169, 196, 225, 256, 289],
       [324, 361, 400, 441, 484, 529],
       [576, 625, 676, 729, 784, 841]])

In [21]:
b = b.reshape(6,5)
a.dot(b)

array([[ 275,  290,  305,  320,  335],
       [ 725,  776,  827,  878,  929],
       [1175, 1262, 1349, 1436, 1523],
       [1625, 1748, 1871, 1994, 2117],
       [2075, 2234, 2393, 2552, 2711]])

주의!!! broadcasting 연산  
행렬, 스칼라  
행렬, 벡터  
벡터, 벡터  

In [22]:
#broadcasting 연산
a + 3

array([[ 3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32]])

In [23]:
# 이거도 브로드캐스팅
a <4

array([[ True,  True,  True,  True, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [24]:
np.all(a<4)

False

In [25]:
np.any(a<4)

True

In [28]:
np.where(a<4)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))

boolean index
- 특정 조건에 따른 값 배열형태로 추출
- Comparison operation 함수들도 모두 사용가능

In [31]:
test = np.array([1,2,3,4,5,6,7,8],float)
test[test>3]

array([4., 5., 6., 7., 8.])

fancy index

In [32]:
a = np.array([1,2,3,4],float)
b = np.array([0,0,1,2],int)
a[b]

array([1., 1., 2., 3.])

In [33]:
a.take(b)

array([1., 1., 2., 3.])

In [37]:
# [row,col] 가능
a = np.array([[1,2],[3,4]])
b  =np.array([1,0],int)
c = np.array([0,0],int)
a[b,c]

array([[3, 4],
       [1, 2]])

In [40]:
a= np.loadtxt("./resources/numbers.txt")
a

ValueError: could not convert string to float: '1   2   3   4   5'